[package]
name = "superqueue"
version = "0.1.0"
edition = "2024"
authors = ["alexdesander"]

[dependencies]
crossbeam-channel = "0.5"
rand = { version = "0.9", default-features = false, features = ["small_rng", "thread_rng"] }
rustc-hash = "2.1"
thiserror = "2.0"
